### ISSUE TITLE
the purpose of BackoffIdleStrategyPrePad

### ISSUE THREAD

**Issue by zhutan** [real-logic/agrona#147]
Hi, 

I am writing my version of BackoffIdleStrategy to work with an old Linux kernel when using Aeron and noticed the BackoffIdleStrategyPrePad class which defines 12 longs that seems not used. What is the purpose of it and do I need to copy them too in MyBackoffIdleStrategy?

Many thanks in advance.

**Comment by nitsanw** [comment]
The BackoffIdleStrategy has rapidly updated counters in the case where it is used. While we may not particularly care about the idle thread suffering from cache misses (since it's got nothing to do), these rapidly updating counters may well be next to a concurrent data structure which will be accessed by another thread. The padding is a means of isolating this noise from other threads. For more info look into False Sharing.
