### ISSUE TITLE
Unsafe.allocateMemory wraping un UnsafeBuffer to overcomming Buffer and Array size limitations

### ISSUE THREAD

**Issue by sirinath** [real-logic/Agrona#30]
Current design the memory size is limited to array or buffer size. Give the ability for UnsafeBuffer to wrap off heap memory. 

This will need a Cleaner also deallocate memory if you forget.

**Comment by mjpt777** [comment]
I don't understand what you are asking for. If this is to have long indexes and wrapping larger memory ranges then, I answered that in your other question on long indexes and lengths.

If you allocate off-heap with Unsafe.allocateMemory then it is your responsibility to free that memory and beyond the scope of UnsafeBuffer design.

**Comment by sirinath** [comment]
Add an constructor and wrap function like `UnsafeBuffer(long memoryAddress, long size)`

**Comment by mjpt777** [comment]
This method is not appropriate on its own. If added it should only be in the context adding long indices.

**Comment by RichardWarburton** [comment]
@sirinath I think conceptually what you want is the ability to wrap over multiple buffers here. A lot of the issues you filed seem to be in the same vein - long indexes etc. You can do this yourself and have a class that wraps multiple UnsafeBuffer instances if you want.

In the projects we've been working on that use Agrona we haven't really hit a need for this functionality, because abstracting over multiple buffers has happened higher up the stack. For example Aeron is conceptually an infinite log buffer and we don't want to try and solve everyone's use cases - just focus on our own.
