### ISSUE TITLE
ClassCastException in Unsafe buffer wrapping a HeapByteBufferR

### ISSUE THREAD

**Issue by robertroeser** [real-logic/Agrona#66]
Hi,

I'm getting a class cast exception using an UnsafeBuffer. Looks like HeapByteBufferR doesn't implement DirectBuffer and is causing problems. Here's the pertinent stack trace fragments:

```
java.lang.ClassCastException: java.nio.HeapByteBufferR cannot be cast to sun.nio.ch.DirectBuffer
	at org.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:891)
	at org.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:869)
```

Thanks,
Robert

**Comment by mjpt777** [comment]
What JDK and by what means have you created the ByteBuffer?

**Comment by mjpt777** [comment]
Also what version of Agrona are you using?

**Comment by mikeb01** [comment]
The problem is that the buffer that is been passed to UnsafeBuffer is a readonly one.  HeapByteBufferR will return false when calling `hasArray()` despite being heap allocated.  The `wrap` call [uses this to determine](https://github.com/real-logic/Agrona/blob/master/src/main/java/org/agrona/concurrent/UnsafeBuffer.java#L205) if this should be treated as a heap or direct buffer.

**Comment by mjpt777** [comment]
@mikeb01 I just noticed this. Seems ready-only heap buffers don't give the wrong answers to `hasArray()` and throw and exception on `array()`.

**Comment by mjpt777** [comment]
This should now be consistent across direct and heap buffers.
