### ISSUE TITLE
DynamicCompositeAgent remove can cause race between onClose and doWork

### ISSUE THREAD

**Issue by nitsanw** [real-logic/Agrona#99]
see relevant TODO here: https://github.com/real-logic/Agrona/blob/master/agrona/src/main/java/org/agrona/concurrent/DynamicCompositeAgent.java#L214

Essentially, remove is threadsafe in it's list manipulation, but the old list may be iterated through by an AgentRunner which will call doWork after onClose has happened or as it is happening. A possible solution is to have a work counter (incremented by the doWork loop on execution) used to delay the close effect until a further iteration has run.

**Comment by mjpt777** [comment]
There is also a race between `onClose()` and `remove(Agent)`

**Comment by mjpt777** [comment]
Putting a work counter in here would be bad for performance. We need a different solution.

**Comment by mjpt777** [comment]
There is no race with `doWork()` and `onClose()` as onClose() should not be called until the doWork() method has returned and will not be invoked again. Look to he standard `AgentRunner`. Same as `onStart()` should be called before `doWork()` is ever called. The only true race is onClose and remove(Agent).

We can address all of this more simply. We can specify that administrative action must be called from a single thread and clarify the other behaviour in documentation.

**Comment by mjpt777** [comment]
It is also worth considering that `onStart()` and `onClose()` are specified to be called on the same thread as `doWork()`. This would help with issues like biased locking. This makes the whole thing much cleaner.

**Comment by mjpt777** [comment]
I think I know a better way to do this. I'll pick it up today.

**Comment by nitsanw** [comment]
> There is no race with doWork() and onClose() as onClose() should not be called until the doWork() method has returned and will not be invoked again. Look to he standard AgentRunner. Same as onStart() should be called before doWork() is ever called. The only true race is onClose and remove(Agent).

From a single Agent point of view, sure. For the sake of this discussion we must consider a DynamicCompositeAgent (lets call it _parent_) executed by an AgentRunner. Its spinning in doWork, while other threads are adding/removing agents. Adding will imply onStart should be executed, removing will imply onClose needs to run. So for _parent_ there's no race between doWork and onClose, but for children there's a risk. Similarly onClose for the _parent_ can race with remove to trigger onClose on the child concurrently.

> It is also worth considering that onStart() and onClose() are specified to be called on the same thread as doWork().
onStart() and doWork() are to be called from the executing thread, onClose is called by the closing thread, at least in the current AgentRunner.

**Comment by mjpt777** [comment]
I've changed the implementation. @RichardWarburton it would be good if you can confirm this would work for you?

**Comment by RichardWarburton** [comment]
@mjpt777 I think overall it looks like it work work well. I've got a few thoughts:

1. You check that the Agent elements of the array aren't null, but you don't do this for the List based constructor. ArrayList can contain nulls, shouldn't they be consistent?
2. Thinking about it do we want the add and remove methods to just yield for idle, or should they take an idle strategy?
3. I kind of felt that an array was a better choice than an arraylist. Iterating over it is a common operation, whilst adding/removing are uncommon.
4. Regardless of container choice if you're iterating over it using a for loop isn't it better to load the agents field into a local variable and use that. I think Nitsan benchmarked it.
5. IMHO The add method should document that if the onStart() method throws an Exception that the agent isn't added.
6. And least importantly, is there any reason to manually null check and throw the exception rather than use Agrona's Verify.notNull(); method or even Objects.notNull() in the JDK?

**Comment by mjpt777** [comment]
@RichardWarburton Thanks. I've applied your feedback. The only thing is the idle strategy which I think does not make sense. This is highly unlikely to contend and if so then a Thread.yield() should be fine.

**Comment by mjpt777** [comment]
@RichardWarburton I've addressed your concern about IdleStrategy by making the methods tryAdd(Agent) and tryRemove(Agent) so that they are non-blocking. You can spin or failure or employ your own IdleStrategy.

**Comment by RichardWarburton** [comment]
I think that's a good approach.
